const state={topics:[],category:'All',saved:new Set(JSON.parse(localStorage.getItem('quoriya-saved')||'[]'))};
const $=s=>document.querySelector(s);
async function init(){const r=await fetch('data/topics.json');const data=await r.json();state.topics=data.topics;renderFilters(data.categories);renderTopics();renderPaths();renderSaved();$('#year').textContent=new Date().getFullYear();setupUI();}
function renderFilters(categories){$('#categoryFilters').innerHTML=categories.map(c=>`<button class="filter-btn ${c==='All'?'active':''}" data-cat="${escapeHtml(c)}">${escapeHtml(c)}</button>`).join('');document.querySelectorAll('.filter-btn').forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;document.querySelectorAll('.filter-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderTopics($('#searchInput').value.trim());});}
function renderTopics(query=''){let list=state.topics.filter(t=>state.category==='All'||t.category===state.category);if(query)list=list.filter(t=>(t.title+' '+t.description+' '+t.category+' '+t.tags.join(' ')).toLowerCase().includes(query.toLowerCase()));$('#topicGrid').innerHTML=list.length?list.map(card).join(''):`<div class="empty">No topics found. Try another search or category.</div>`;document.querySelectorAll('.save-btn').forEach(b=>b.onclick=()=>toggleSave(b.dataset.id));if(query){$('#searchResults').hidden=false;$('#searchResults').innerHTML=`Showing <strong>${list.length}</strong> result${list.length===1?'':'s'} for “${escapeHtml(query)}”`; }else $('#searchResults').hidden=true;}
function card(t){return `<article class="topic-card"><div class="topic-cover"><span class="topic-icon">${escapeHtml(t.icon)}</span><span class="topic-type">${escapeHtml(t.type)}</span></div><div class="topic-body"><h3>${escapeHtml(t.title)}</h3><p>${escapeHtml(t.description)}</p><div class="topic-meta"><span>${escapeHtml(t.category)} · ${escapeHtml(t.readTime)}</span><button class="save-btn" data-id="${escapeHtml(t.id)}" aria-label="Save ${escapeHtml(t.title)}">${state.saved.has(t.id)?'★':'☆'}</button></div></div></article>`}
function renderPaths(){const picks=state.topics.slice(0,4);$('#pathList').innerHTML=picks.map((t,i)=>`<div class="path-item"><div class="path-num">${i+1}</div><div><strong>${escapeHtml(t.title)}</strong><span>${escapeHtml(t.category)} · ${escapeHtml(t.type)}</span></div></div>`).join('');}
function renderSaved(){const items=state.topics.filter(t=>state.saved.has(t.id));$('#savedGrid').innerHTML=items.length?items.map(card).join(''):`<div class="empty">Your saved topics will appear here.<br>Tap ☆ on any topic to keep it close.</div>`;document.querySelectorAll('.save-btn').forEach(b=>b.onclick=()=>toggleSave(b.dataset.id));}
function toggleSave(id){if(state.saved.has(id))state.saved.delete(id);else state.saved.add(id);localStorage.setItem('quoriya-saved',JSON.stringify([...state.saved]));renderTopics($('#searchInput').value.trim());renderSaved();}
function setupUI(){const input=$('#searchInput');$('#searchForm').onsubmit=e=>e.preventDefault();input.addEventListener('input',()=>renderTopics(input.value.trim()));document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();input.focus()}});$('#themeToggle').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('quoriya-theme',document.body.classList.contains('dark')?'dark':'light')};if(localStorage.getItem('quoriya-theme')==='dark')document.body.classList.add('dark');$('#menuToggle').onclick=()=>$('#mobileMenu').classList.toggle('open');}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
init().catch(err=>{console.error(err);$('#topicGrid').innerHTML='<div class="empty">Could not load content. Check that you opened the site through GitHub Pages or a local web server.</div>';});
